"""empty message

Revision ID: 29756ccec8c4
Revises: 7f6414b8d90c
Create Date: 2020-03-24 05:32:18.883266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29756ccec8c4'
down_revision = '7f6414b8d90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_hero_name'), 'hero', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hero_name'), table_name='hero')
    # ### end Alembic commands ###
